###############################################################################
#
# MIT License
#
# Copyright (c) 2025 Advanced Micro Devices, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
###############################################################################
import abc
import copy
import datetime
import logging
import uuid
from typing import Any, Optional, Union

from nodescraper.constants import DEFAULT_EVENT_REPORTER, DEFAULT_LOGGER
from nodescraper.enums import EventCategory, EventPriority
from nodescraper.models import Event, SystemInfo, TaskResult

from .taskresulthook import TaskResultHook


class SystemCompatibilityError(Exception):
    """Exception raised when system has invalid attributes for the task"""

    pass


class Task(abc.ABC):
    """Parent class for all tasks"""

    TASK_TYPE: str

    def __init__(
        self,
        system_info: SystemInfo,
        logger: Optional[logging.Logger] = None,
        max_event_priority_level: Union[EventPriority, str] = EventPriority.CRITICAL,
        parent: Optional[str] = None,
        task_result_hooks: Optional[list[TaskResultHook]] = None,
        event_reporter: str = DEFAULT_EVENT_REPORTER,
        session_id: Optional[str] = None,
        **kwargs: dict[str, Any],
    ):
        """Creates a Task instance.

        Args:
            system_info (SystemInfo): system info object for target system for data collection
            logger (Optional[logging.Logger], optional): python logger object. Defaults to None.
            max_event_priority_level (Union[EventPriority, str], optional): priority limit for events. Defaults to EventPriority.CRITICAL.
            parent (Optional[str], optional): parent task identifier. Defaults to None.
            task_result_hooks (Optional[list[TaskResultHook]], optional): list of task result hooks. Defaults to None.
            event_reporter (str, optional): Reporter string stored on emitted events. Defaults to DEFAULT_EVENT_REPORTER.
            session_id (Optional[str], optional): session identifier. Defaults to None.

        Raises:
            ValueError: Will raise a ValueError when the session_id is not a Valid UUID string.
        """
        if logger is None:
            logger = logging.getLogger(DEFAULT_LOGGER)
        self.system_info = system_info
        self.logger = logger
        self.event_reporter = event_reporter
        self.max_event_priority_level = max_event_priority_level
        self.parent = parent
        if not task_result_hooks:
            task_result_hooks = []
        self.task_result_hooks = task_result_hooks

        if session_id is None and "session_id" in kwargs:
            session_id = kwargs.pop("session_id")  # type: ignore[assignment]
        if session_id is not None:
            try:
                uuid.UUID(str(session_id))
            except (ValueError, TypeError, AttributeError) as e:
                raise ValueError(
                    f"session_id must be a valid UUID string, got: {session_id}"
                ) from e
        self.session_id: Optional[str] = str(session_id) if session_id is not None else None

        self.result: TaskResult = self._init_result()

    @property
    def max_event_priority_level(self) -> EventPriority:
        """maximum priority level for events generated by task

        Returns:
            EventPriority: max priority level enum
        """
        return self._max_event_priority_level

    @max_event_priority_level.setter
    def max_event_priority_level(self, input_value: Union[str, EventPriority]):
        if isinstance(input_value, str):
            value: EventPriority = getattr(EventPriority, input_value)
        elif isinstance(input_value, int):
            value = EventPriority(input_value)
        elif isinstance(input_value, EventPriority):
            value: EventPriority = input_value  # type:ignore
        else:
            raise ValueError(f"Invalid type for max_event_priority_level: {type(input_value)}")

        self._max_event_priority_level = value

    def __init_subclass__(cls, **kwargs) -> None:
        """Validates that the subclass contains a TASK_TYPE attribute which is not None."""
        super().__init_subclass__(**kwargs)
        if cls.TASK_TYPE is None:
            raise TypeError(f"No value provided for TASK_TYPE in task class {cls.__name__}")

    def _build_event(
        self,
        category: Union[EventCategory, str],
        description: str,
        priority: EventPriority,
        data: Optional[dict] = None,
        timestamp: Optional[datetime.datetime] = None,
    ) -> Event:
        """This will build an event

        Args:
            category (Union[EventCategory, str]): The category of the event.
            description (str): The description of the event, typically a human-readable message.
            priority (EventPriority): The priority level of the event.
            data (Optional[dict], optional): Additional data associated with the event. Defaults to None.
            timestamp (Optional[datetime.datetime], optional): The timestamp of the event. Defaults to None.

        Returns:
            Event: The constructed event object.
        """
        if data is None:
            data: dict[Any, Any] = {
                "task_name": self.__class__.__name__,
                "task_type": self.TASK_TYPE,
            }

        else:
            # Copy to avoid mutating the caller's dict
            data: dict[Any, Any] = copy.copy(data)
            data["task_name"] = self.__class__.__name__
            data["task_type"] = self.TASK_TYPE

        if self.parent:
            data["parent"] = self.parent

        if self.session_id is not None:
            data["session_id"] = self.session_id

        if self.system_info.metadata:
            data["system_metadata"] = copy.copy(self.system_info.metadata)

        if priority > self.max_event_priority_level:
            priority = self.max_event_priority_level

        event = Event(
            reporter=self.event_reporter,
            category=category,
            description=description,
            priority=priority,
            data=data,
        )

        if timestamp:
            event.timestamp = timestamp

        return event

    def _log_event(
        self,
        category: Union[EventCategory, str],
        description: str,
        priority: EventPriority,
        data: Optional[dict] = None,
        timestamp: Optional[datetime.datetime] = None,
        console_log: bool = False,
    ):
        """Log an Event

        Args:
            category (Union[EventCategory, str]): The category of the event.
            description (str): The description of the event, typically a human-readable message.
            priority (EventPriority): The priority level of the event.
            data (Optional[dict], optional): Additional data associated with the event. Defaults to None.
            timestamp (Optional[datetime.datetime], optional): The timestamp of the event. Defaults to None.
            console_log (bool, optional): Whether to also log the event to the console. Defaults to False.
        """
        event = self._build_event(
            category=category,
            description=description,
            priority=priority,
            data=data,
            timestamp=timestamp,
        )

        if console_log:
            level = getattr(logging, priority.name, logging.INFO)
            prefix = ""
            if data:
                et = data.get("exception_type")
                if et:
                    prefix = f"[{et}] "
            self.logger.log(level, "%s%s", prefix, description)
            if data:
                tb = data.get("traceback")
                if tb:
                    tb_text = "".join(tb) if isinstance(tb, list) else str(tb)
                    if tb_text.strip():
                        self.logger.log(level, "Traceback:\n%s", tb_text.rstrip())
                det = data.get("details")
                if det and not tb:
                    self.logger.log(level, "Details: %s", det)

        self.result.events.append(event)

    def _init_result(self):
        result = TaskResult(task=self.__class__.__name__, parent=self.parent)
        return result

    def _run_hooks(self, result, **kwargs):
        for hook in self.task_result_hooks:
            hook.process_result(result, **kwargs)
