# workflow to validate code formatting using pre-commit hooks
name: Code Quality Check

permissions:
  contents: read

on: [pull_request]

jobs:
  pre-commit:
    runs-on: [ self-hosted ]
    container: python:3.10

    steps:
      - uses: actions/checkout@v3
      - name: setup environment
        run: |
          ./dev-setup.sh
      - name: run pre-commit hooks
        run: |
          pre-commit run --all-files --show-diff-on-failure --color=always
      - name: Print message on failure
        if: failure()
        run: |
          echo "### :x: Pre-commit hooks failed. Please check logs for changes needed" >> $GITHUB_STEP_SUMMARY
