name: Python Unit Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  run_tests:

    runs-on: [ self-hosted ]
    container: python:3.10

    steps:
    - uses: actions/checkout@v3
    - name: Install package
      run: |
        ./dev-setup.sh
    - name: Run unit tests
      run: |
        pytest -s test/unit
